# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:BQsV96lTDJPogwgYL2tQJ5Kl5XRmvDlkU2fyP2UoS5onL2ssQVJCHQ==,iv:cMkc5FHqFq36ROg8Dd6G+x3HAlAduu43IhESNHR9TIs=,tag:DZtEkzH0D4rO1EqH5feDSA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1z2fh4reltz3wu2vz3v8fg4lg5xq2leedrha9zunm95ycy4tpmgqqf33wdp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRW5vdVVFdWlvZnVHdThB
        Mlp3S2poMUUydXg2Uk5Gbm1hUzNlc0p3Skg0CksvQWxmQ0JaSW9vYXdEWnNEQUx6
        RHF6VW5ld3VISkdtbFJvL3pRTGJqd2cKLS0tICtqcUZCOVo4NzhSY3cxZG5qaFh2
        RWkwYnpTYldmVHlTelZjU21mYjlFQTQKxcn2TxVGklAwZkvMZIu7V46Un5W1N2rw
        AZOh6AjtAUzmXMrMGcXo3eFtobyxSLayilbXmeDBaby5LgxVpJt4ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-05T18:36:12Z"
  mac: ENC[AES256_GCM,data:aEKqyjsIggf5XnD5didc5/Fn9FYTbaHFsYAaHg2u+AjUn0QbEXb3VrXwD/Y/Q1gBQopfd1lvgrBy2OUqE0btAebKYZiuR1P2K2Rb4SUETyAbFAIo6wM0xaoj/gEIe6v7J5HmqkVvuLcr93VP8oa7iJOwlATQNaEkTW49OKHstaU=,iv:auhcv5nPAfjRS/XysTgadeFyRIpoaBEG3KY3OoJ3M6U=,tag:EA4S0tPHyrmj+b1WK7Ra9A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
