---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: ntfy
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
