apiVersion: v1
kind: Secret
metadata:
  name: kritika-postgres-credentials
  namespace: kritika
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:/1zIET/qpg==,iv:53yXfnCX3wB2fr7wUnpRhTJtvCr2A03Q+zDmCQHkoZk=,tag:Kkxx0/P8xYMzE7rFNS+5ig==,type:str]
  password: ENC[AES256_GCM,data:om0+hTtejaGiL/3CGpOH0h8cTnCxiDjHAw7Ub6Ge/tAcNFEopF6FhV4+uZu4kbrJ,iv:wLWmrMS0dDjx1Q5r5wk2TkubboYD0hZf+a3wTvzWzOA=,tag:++n9N5PxRFcm5XRjN0ZzRQ==,type:str]
  uri: ENC[AES256_GCM,data:GzEl7QJTDTA6pXGAXuu/P62LtYZnPj/QudDVzN8ckyxNcdlj02krRNm7vEwZH25pScb1HCNHEKhgOgXJbfIviTYzx9eG7gXtb2a45ke4uK3Gn0ZGucJ2eCXR5BMJTCZ6vbbnTVQQ7alANOL9ZgWAZE7iNH6RBFmID9fZdQtNsHdrTwp9NwiVjhw9kqeesfvx0H4u,iv:0JmRuY104hNXDKUITt9iX/9ZRmfd7iGxaoGRjlyeT28=,tag:dKIPHY8aCDjYIxx2jvntDg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK1pVbmpZd3BsdHVMSDRS
        OVdYaUJOU28yaFl2cndqOFVOVHkxWU04MTNjCmExMGlSdW5VQW1tcDhGdys0WGxK
        TkNzQ3R3cnpHY2RJTjlubXcxUmJqc0EKLS0tIFRMVmJPRkFGWFpOTTZOYWNVZVNM
        UDlrbEJWV2FQamRud3FZNldXMXFjSlEKDftyQwzov+bO+mZti4vD7Vw0PLmnAEE8
        St/fES61GoYXS9ZeVAUKcUBI+i91tcld8ocnxUZR6bIwGG7ZbEInkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z2fh4reltz3wu2vz3v8fg4lg5xq2leedrha9zunm95ycy4tpmgqqf33wdp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T14:12:17Z"
  mac: ENC[AES256_GCM,data:HR3kTNTOagOzP91YX1gzGrD7B4V5u0/eKSl0dfcjVLdxMi9lXO8tQNzsuquiabSAPVaQLsM/JbJla42x22yh4G1Zz7NDzYQEcKX3t4PMyLImq8J46CYTDf2Bis8aGCTNT7Foq3Lmu+ROCI+1fAWrofpg3cvDrMKY5PvyTODUQFU=,iv:ocinAvbOTtyCh/A3RamPLuOCeuKecUR1Y6e8CaGsWE8=,tag:7nWXg5s3go6he1yHSUiqSg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: kritika-postgres-app
  namespace: kritika
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:fsDyG+5hH98J8ts=,iv:U20RYm/jKVTmcs/nv6ziH6oxqjf/Ip7xy77xOcSdT8U=,tag:hYZgYnxpNRGd221BJvIz9A==,type:str]
  password: ENC[AES256_GCM,data:+Tctk/DTuYCJ926SrZZ7gBV8mvZ0HCf8c5y/ZD0ZGbkaZ2HhwHMOBXsa0VQPfz7v,iv:jmlTo8yLKaVL+BaKLqHmu/3cODA+1OYwScqVgmHjX3s=,tag:u+0eEWwnUrpNyCSf/lsbcg==,type:str]
  uri: ENC[AES256_GCM,data:dcfSPBHlWYtin6tf9Gd+xO6h7exh6IfxGlhhJomtWg2uK/SVkCYgMGSvT5vwcTYBCWSbGGhqnmrYbpgEOCFc7vAs/etysbiMJsEX8CTWsNv6F32uHXpI1MGFJF56dJDKBVO+D7PGeNHLyO5xkx8PuhBqhB09LoEk01t3DC0S41O225uLsaTl9ywdCncJWrGv2pJjvhk/ow==,iv:x8HtXUtPMwI90FucxNUP0i7HY636Q3PZDh7fX9WUBAM=,tag:NDeiLCZetvpqALenkzCZMw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK1pVbmpZd3BsdHVMSDRS
        OVdYaUJOU28yaFl2cndqOFVOVHkxWU04MTNjCmExMGlSdW5VQW1tcDhGdys0WGxK
        TkNzQ3R3cnpHY2RJTjlubXcxUmJqc0EKLS0tIFRMVmJPRkFGWFpOTTZOYWNVZVNM
        UDlrbEJWV2FQamRud3FZNldXMXFjSlEKDftyQwzov+bO+mZti4vD7Vw0PLmnAEE8
        St/fES61GoYXS9ZeVAUKcUBI+i91tcld8ocnxUZR6bIwGG7ZbEInkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z2fh4reltz3wu2vz3v8fg4lg5xq2leedrha9zunm95ycy4tpmgqqf33wdp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T14:12:17Z"
  mac: ENC[AES256_GCM,data:HR3kTNTOagOzP91YX1gzGrD7B4V5u0/eKSl0dfcjVLdxMi9lXO8tQNzsuquiabSAPVaQLsM/JbJla42x22yh4G1Zz7NDzYQEcKX3t4PMyLImq8J46CYTDf2Bis8aGCTNT7Foq3Lmu+ROCI+1fAWrofpg3cvDrMKY5PvyTODUQFU=,iv:ocinAvbOTtyCh/A3RamPLuOCeuKecUR1Y6e8CaGsWE8=,tag:7nWXg5s3go6he1yHSUiqSg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: kritika-postgres-runner
  namespace: kritika
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:xDg3/s7OvJBrIY8KbR8=,iv:1lCHfRcpCM8SbW9sT+Sw1K9Mew/WMVPfd3KK6O/V760=,tag:ONm12SsL9JUqLw095DwkPQ==,type:str]
  password: ENC[AES256_GCM,data:9eErcGubwerReJJLqKrz639AMWlK8vbm+8AAN4rsjbMPTyJKRHBoL7Gx8g9ctlNH,iv:JW65hyH6qoEPFQCJ0yp+yM+ZAdwNFVJiKETvsHf5tqk=,tag:Hlyga2BYYah2GZrqFf6kUQ==,type:str]
  uri: ENC[AES256_GCM,data:zQdVZetbaAi+4ahcNIlNSXpif1hcZhI4tlyqwuYXLtzM4baXDQ3VNcHOFu1nDSdLvVYTJlTDQ9P6NpknXkW3TzyYPJpFXXzBeJvgwjqAGu5hBnS4K/CwL3hIlt3E38nfg7/eAys/4RxZ1XkCP8HW0pwQG0Dv5koCUvGXJD0ZFCaDsKCR6UprZQevhZMlJEMlHu9koroqHIfNGg==,iv:uwACqbjYsxZCAKjsaH80pyw/Sb/Rohb8rX/cGS2o0Ks=,tag:SUCFQYvoa4MmAXEbEp1yyA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK1pVbmpZd3BsdHVMSDRS
        OVdYaUJOU28yaFl2cndqOFVOVHkxWU04MTNjCmExMGlSdW5VQW1tcDhGdys0WGxK
        TkNzQ3R3cnpHY2RJTjlubXcxUmJqc0EKLS0tIFRMVmJPRkFGWFpOTTZOYWNVZVNM
        UDlrbEJWV2FQamRud3FZNldXMXFjSlEKDftyQwzov+bO+mZti4vD7Vw0PLmnAEE8
        St/fES61GoYXS9ZeVAUKcUBI+i91tcld8ocnxUZR6bIwGG7ZbEInkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z2fh4reltz3wu2vz3v8fg4lg5xq2leedrha9zunm95ycy4tpmgqqf33wdp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T14:12:17Z"
  mac: ENC[AES256_GCM,data:HR3kTNTOagOzP91YX1gzGrD7B4V5u0/eKSl0dfcjVLdxMi9lXO8tQNzsuquiabSAPVaQLsM/JbJla42x22yh4G1Zz7NDzYQEcKX3t4PMyLImq8J46CYTDf2Bis8aGCTNT7Foq3Lmu+ROCI+1fAWrofpg3cvDrMKY5PvyTODUQFU=,iv:ocinAvbOTtyCh/A3RamPLuOCeuKecUR1Y6e8CaGsWE8=,tag:7nWXg5s3go6he1yHSUiqSg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
