apiVersion: v1
kind: Secret
metadata:
  name: kopiur-repository-secret
  namespace: kopiur-system
type: Opaque
stringData:
  KOPIA_SFTP_KEY_DATA: ENC[AES256_GCM,data:uiIa1uktlt2Iq00hSvINU+p2WVRi8XamZl6NTjS/5XmV/5tmf5CIeKD5XBeTqj9wkCKMuPxfce08sNGWeyzHyclpECSCVGTru7e9uegIYfyhWngJF1lngXqJPtVFYmXx+8+WaYdYMo6/6XRFS7JYYTfFXiB5O7p6hWP45L7jhYJqeMTSH6cu2twZtvESegHTkt4JaJEAz2sOppr7gZPUiPlRDbk+4vSwBAJQr/2CmLJQK8Ih6Qx9Rch3WEvpqkoQn4fQrrfFxTqduIHJdAIWnz60b7K/xZKzWSApp8KKp8WGzxd7JnjgCcDfrJhIfln9+/xvp7eD6rVArxAyXUQgrKhWlXLJJup8ouW9oCVZAtethHoIWvsH/1NWxZTXWMIskKRC+VIjG3tKA74U3jm5aYSD0LO2yCn2iFvGAbEWv1RMM2YH3istifb8NPvR94HmkcYGQADgIVJkeUG/2Y5rZPEPV2t8G3j7qJ7sa1X9/DTur7oyXU1WYfwmndjO3WcgGNDm3Km9LNv+B4DHJZeq,iv:s6re80BgGWQCOWBGNXa68JRhqfB3Sn45KenHBd5cSuI=,tag:/TlxCO+DrZvl+MgVrae1Tw==,type:str]
  KOPIA_SFTP_KNOWN_HOSTS: ENC[AES256_GCM,data:wr9BirMppxOhTDY+WMZCFO/UedxTzFOiEkDPhMJsPVMn06AmeHhX/rdk2e9o5Uhc4xwWR/1q55kh+KjJ5MHN5LNjuWp/iXR/+BE1b1UoCro0mQKh0s5RbjWyUg==,iv:fPOIdwYHS6jqr9jp7sho/66PtCsk54xlSPYrBanEvrk=,tag:KR2YCIeYJSrkax5SUpVSUQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:MTQKGijdnvGQqD+QwrDhJqyyxH8VfwCRRr143Cuh+jnBWjhwA8ZaoQ==,iv:eGYW5/M00JFljg3H8Lz1gtKuKS+VzncKSVW3mxkwbGU=,tag:RICqJ56AzIIJXZRUs8070g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RVVUVDZmamp3MW8zSkFN
        eTdtTGF5ZkxnR2U2NlQwUzNEZEVwNDhwOHdvCm9JRHZPMDFyRUFGaktadTV1azBa
        V2RIejNZM2VzaTM2dXdwYW1nTkVqd0EKLS0tIEN2TDhhMkdRY0FkZE1MaTB0Z3Av
        QXNPMlZyZWU0UTVmb1FYSFkzMkhVY3MKjFUiWevJIz9Kc8Fiee3On4E5NAhPRkZ2
        knewQzXnCFISBZhJPajx/CJ5Rzu4VVPgyf8F1uij7CGBCHug10DlWw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z2fh4reltz3wu2vz3v8fg4lg5xq2leedrha9zunm95ycy4tpmgqqf33wdp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T16:07:06Z"
  mac: ENC[AES256_GCM,data:WHVWhHarWMcRkaI4pmO2tW8DwX6K/Sgu3mVwSzmO7sxeIO6GrZNEqITb6jH+Feecli1SP2CRkfgmm6PzgiPoNp/eXen5FF1tTyAG4xWLByrPcMyTotdchib7/kCSw//HxozCBvAqc7pGF51gzoShTDxnFmbzGeCWniikJyjuypE=,iv:umzdXaDGzUVzVpzl0sr8ZZLUC+KYbclB+bewumyZG60=,tag:kJw+kAu0e3j60/S9Fklotg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
