apiVersion: v1
kind: Secret
metadata:
  name: kopiur-repository-secret
  namespace: kopiur-system
type: Opaque
stringData:
  KOPIA_SFTP_KEY_DATA: ENC[AES256_GCM,data:uiIa1uktlt2Iq00hSvINU+p2WVRi8XamZl6NTjS/5XmV/5tmf5CIeKD5XBeTqj9wkCKMuPxfce08sNGWeyzHyclpECSCVGTru7e9uegIYfyhWngJF1lngXqJPtVFYmXx+8+WaYdYMo6/6XRFS7JYYTfFXiB5O7p6hWP45L7jhYJqeMTSH6cu2twZtvESegHTkt4JaJEAz2sOppr7gZPUiPlRDbk+4vSwBAJQr/2CmLJQK8Ih6Qx9Rch3WEvpqkoQn4fQrrfFxTqduIHJdAIWnz60b7K/xZKzWSApp8KKp8WGzxd7JnjgCcDfrJhIfln9+/xvp7eD6rVArxAyXUQgrKhWlXLJJup8ouW9oCVZAtethHoIWvsH/1NWxZTXWMIskKRC+VIjG3tKA74U3jm5aYSD0LO2yCn2iFvGAbEWv1RMM2YH3istifb8NPvR94HmkcYGQADgIVJkeUG/2Y5rZPEPV2t8G3j7qJ7sa1X9/DTur7oyXU1WYfwmndjO3WcgGNDm3Km9LNv+B4DHJZeq,iv:s6re80BgGWQCOWBGNXa68JRhqfB3Sn45KenHBd5cSuI=,tag:/TlxCO+DrZvl+MgVrae1Tw==,type:str]
  KOPIA_SFTP_KNOWN_HOSTS: ENC[AES256_GCM,data:e28msEauCTvRtys9DFEHGtnOYQ2fvhR1FzE1yuxF/HLcMWThErtcc0PdjhSAoJiRYYv9AiKmBXAg371MSnpvxpXJCSGmWEI3QpzZPiplFCVtI1AfHUIYhh6X7eOme4GzAE+7cu3T0tDAawDlF3+ST0PtN3fdx+skxRlP2m5F+CarIHzVVxwJIV7akOdrOgazpMXBdxk12XpSO1dSQ4H4/rS9I0tDAUpLDt6mSq8l42+UED36kSYxPf+Ml4BbjOygyfXv+dgOzNhTIklI+NuxWCQX5i3Ny4GsKg1htL0Scb3IEUjgHFB/0W+gutIjGOWm2rkEkcu3EsQNo203IcsdJVLhNwqD0sDxzP8lpWpUC6YIp1nO1F6h2zK5jK/3Y94dA1KSedDVwd5Axsr7/0CxDuKpoPiFtqtdWIl6bViE0SJnm4YHuIRqUHnXEyVo6xoN3Y0rpv82k2QvCLkV0L33Tk+zSvmK1BjPIqOCu+IENqfX5ssMBBbtbKdy1lN0rf+FjHikSXSJCXBamzvv/NGfPpPKlLhjTcqcREu+QNplOHa41FnwJ7sriaHBXAfqI3uJBKVnIOh79T3qo0DoMtL5xZY/wYAiqpnE8lCg/qnZCHx4Z65igJgsBhWc6IUCQhlDOjmcBLXGMlly7P+I8+E5RSdbLCpjYoQu2usPL5Uv1z1bgAMPPEBq49PPolXh6XYzxZAtfCBDaVfaswHlITpr+kTjKKLK5jbMOvSm2y22s0WmeQa6pGH3X7DPE00e6p+ojDkyckjWlunXHD1x0JaDmxpc0kWtrow1TCZGtJOPl65WAw2cw85SzyT57hmbOamB+nTjlWhw96nxqxvk51SqCGKFrwkW7OImFyrwwJk7JHPgAYlu1vNMKg80Ba/6GNPbxJCvoHn4w2Dlpnlssm9iUXnPFX7ocmGdsQ2RgGaDzmuTx1mRnFqwp+5RGzEm/sEeI3OfRMNC4pl7BZxM+bD0bXvsCx29es4S3LD8HkzIjZkSkkcMN4XSXPPs3xZiI2wubZuUpYMODS/4N4Uy9q9B0eXHutBTdWxD+3hytIStJOvPtxY6dglRhwLeSHx0Vk7dKQLX8jnuFMbOi1hJ,iv:Bf3ygxykHZWXGiCAvXZeZrxV+iZ6TQpnnr76gVHheaA=,tag:9K/0YYKLwiW3hldm+DC+4g==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:sixYEl4FBEndCyA01ibxsP2ynxwMv0IIbuJdywzpMB9aVJgCvPYvGA==,iv:oofc9OXs349sH3zquXy65yHU/he7MI1UNYROMlNlgH4=,tag:Gl0cTJUOi0hh1K5TyrBoyQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RVVUVDZmamp3MW8zSkFN
        eTdtTGF5ZkxnR2U2NlQwUzNEZEVwNDhwOHdvCm9JRHZPMDFyRUFGaktadTV1azBa
        V2RIejNZM2VzaTM2dXdwYW1nTkVqd0EKLS0tIEN2TDhhMkdRY0FkZE1MaTB0Z3Av
        QXNPMlZyZWU0UTVmb1FYSFkzMkhVY3MKjFUiWevJIz9Kc8Fiee3On4E5NAhPRkZ2
        knewQzXnCFISBZhJPajx/CJ5Rzu4VVPgyf8F1uij7CGBCHug10DlWw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z2fh4reltz3wu2vz3v8fg4lg5xq2leedrha9zunm95ycy4tpmgqqf33wdp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T17:51:51Z"
  mac: ENC[AES256_GCM,data:twcNE33q1sIlVJaqHQsXVGbD5HEhmmqQrebeWQRYy389fS/l/+HeM2EKOSeXsU+w1RYO58Cc6sNnwg+j3ehXLNl2I9gCIyAk74+S6lCn6Fn8ShURjrzpyw4uFxcVxPZifzxdBvp2l07aA46eKYwG6LsVw6iGapkJd6vhUCOWL60=,iv:Hxbd5511OpigNWjXcfRYJxN1wH66SKkr2TugHdWZU/I=,tag:9c6OO8wJDp/Q9KEjf6oDTw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
