# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  api-key: ENC[AES256_GCM,data:fC8KUTXGpzuhInBtsRQ2T0d4jRs5oMDVT44yERxz5wo=,iv:+oRFt1SGjlPG6tZEaaddv8Y0vjBnkNbIVHRaBjBmsEw=,tag:/MF9K98sVYS8iOSMJFbrsg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWm9TWm1oSlpxNC9WOXhQ
        VGlkVEdwZ2hzUEVaUGVCKzBOb3JBRXRYRXcwCjVhbW1neVgxRE9YZ3Bna2Rrbmxo
        Rkw5b0czb0taYittM1lMZHFCa0hCM00KLS0tIGE4N3hFVllGbzZ6MUh2bFI2a2xL
        YWREWGd6WmpsN1ZUQ0s4QzBRTG9EVW8KcYi5Jdf+YE2iJExbQDNOof/cdkgBR/z6
        csI7Kx9jdtxqptxAQVS8XOOs0whP+nU00Nr67Y56s3BPaWjQ553eVA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z2fh4reltz3wu2vz3v8fg4lg5xq2leedrha9zunm95ycy4tpmgqqf33wdp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T09:27:53Z"
  mac: ENC[AES256_GCM,data:d5Xk/E46dPRgZfw1pvhZUtPK3Dj6JWLteYlvslney8XWITRDBHHaQ3ac3f36c3i0rFCkkILpPWIXOjQz247UMpqElL5ET6F9YNk+gXNB/z5oYi3CptvhCotwwIwVsCJlpJTfpyiNAUaTnxG+ciIF6JFXow2vAnTDIF8uobdRJR8=,iv:WkZ0jOfaD1SEDS+pyZ8tjQRh6u//1pXxTwZwJClKmIQ=,tag:wFonJfw4sBB+WPaaE33z+w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
