---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin-config
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: atuin
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
