---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: price-patrol-data
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: price-patrol
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
